sudo: required
dist: trusty

services:
  - docker

install:
  - docker build --rm --file=Dockerfile --tag=rainbeam/solidity-static .
  # create a container to copy files from (can't copy from an image)
  - tmp_container=$(docker create rainbeam/solidity-static sh)
  - docker cp ${tmp_container}:/usr/local/bin/solc .
  - docker cp ${tmp_container}:/usr/local/bin/soltest .

script:
  - echo "no script"

deploy:
  provider: releases
  api_key:
    secure: PZaAm4J8CYNsQV0m1BABO1riPqVSdBcaFKiWcNMsKiGC92xDRXlDkGxM3wEHl2PVzIpsgV9hgVua/XWQDY0I5aUFaQo2GwdNFmeuEMiUGPP31AbEF1O6oKxlu0q88dgrj4vtOVkxi3W4lt2Kw9B5QvhO3GxrSCIHfqWIkWg1UvUYt6X+7+kmFSQ6irDDro3bE7ktbyG5COt59etAr9tjMBqSCp0+Zawe0gTX09AttuUam+VHgUD2lF97mhmstvGLk9Hxi8lHdBhMOQpTlwL59OlPJ3N9mptvBShe6DKuLJM/kn9y1piR1VheBs9hZ/ilNiF4Ufm0yAzmG71E6oLcB+kKqqMCyD1uPJPvxPpxenJvXzweGIRQNEsf/Xmzyi7gkFPnDcMmKpbjxdoJFTnPi0wikJpXbFF43Z4u3OqJHAW58nW4d/qrynfm0ljKprDi6FrZysw27q24tzlDrvY5gQcQpbHMZW9qTQk86K40IYbPPwLOxOewkYGd78Jf6vG4Ujhoz7AGpO8vH8i+rNSco6MWoWwRYkPqOwnRtJHuyDstXRro+XIFAF95XCU6QMMvejMw5/purmGqRj8TlqFVYtRs4n7sK1OnUxh+nfy/CQIhH6wpEJyi9oLsTKTIfc9MiAPuBkay/fMBvv+J59uIeaKCBPETbcGO542N7XGf3wI=
  file:
    - solc
    - soltest
  skip_cleanup: true
  on:
    tags: true
    repo: rainbeam/solidity-static
